# Generated by Django 3.2.8 on 2021-11-16 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=32, verbose_name='Session id')),
                ('quantity', models.FloatField(default=0, verbose_name='Quantity')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Modifying date, time')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_item', to='app_sellers.balances', verbose_name='Reservation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_basket', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Basket',
                'verbose_name_plural': 'Baskets',
                'db_table': 'mp_basket',
            },
        ),
        migrations.AddIndex(
            model_name='basket',
            index=models.Index(fields=['session'], name='idx_session_basket'),
        ),
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together={('session', 'reservation')},
        ),
    ]
