# Generated by Django 3.2.8 on 2021-11-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifying date, time'),
        ),
    ]
