# Generated by Django 3.2.8 on 2021-10-21 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Seller name')),
                ('address', models.CharField(max_length=254, verbose_name='Address')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail address')),
                ('phone', models.CharField(max_length=16, verbose_name='Phone number')),
                ('image', models.ImageField(blank=True, upload_to='files/sellers/', verbose_name='Image (avatar)')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
                'db_table': 'mp_sellers',
            },
        ),
        migrations.CreateModel(
            name='GoodsDescriptionsValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=254, verbose_name='Description value')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_feature', to='app_sellers.goodsdescriptionsvalues', verbose_name='Description item')),
            ],
            options={
                'verbose_name': 'Description value',
                'verbose_name_plural': 'Description values',
                'db_table': 'mp_goods_descriptions_values',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deletion mark')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active flag')),
                ('order_index', models.IntegerField(default=0, verbose_name='Order index')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='app_sellers.goodscategories', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'Goods category',
                'verbose_name_plural': 'Goods categories',
                'db_table': 'mp_goods_categories',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Good`s name')),
                ('limited', models.BooleanField(default=False, verbose_name='Limited edition')),
                ('sales', models.IntegerField(default=0, verbose_name='Sales quantity')),
                ('rating_average', models.IntegerField(default=1, verbose_name='Average rating value')),
                ('rating_total', models.IntegerField(default=0, verbose_name='Total rating value')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deletion mark')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_category', to='app_sellers.goodscategories', verbose_name='Good category')),
                ('description', models.ManyToManyField(db_table='mp_goods_descriptions', related_name='good_descriptions', to='app_sellers.GoodsDescriptionsValues')),
            ],
            options={
                'verbose_name': 'Good item',
                'verbose_name_plural': 'Good items',
                'db_table': 'mp_goods',
            },
        ),
        migrations.CreateModel(
            name='Balances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Good`s quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_balance', to='app_sellers.goods', verbose_name='Good')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_owner', to='app_sellers.sellers', verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
                'db_table': 'mp_balances',
            },
        ),
    ]
