# Generated by Django 3.2.8 on 2021-10-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
