# Generated by Django 3.2.8 on 2021-11-16 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sellers', '0002_alter_goodsdescriptionsvalues_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goods-images/', verbose_name='Image')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_images', to='app_sellers.goods', verbose_name='Goods item')),
            ],
            options={
                'verbose_name': 'Goods image',
                'verbose_name_plural': 'Goods images',
                'db_table': 'mp_goods_images',
            },
        ),

    ]

