# Generated by Django 3.2.8 on 2021-10-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sellers', '0002_sellers_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
