# Generated by Django 3.2.8 on 2021-10-26 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='banner title')),
                ('text', models.CharField(blank=True, max_length=256, null=True, verbose_name='banner text')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/banners', verbose_name='banner image')),
                ('link', models.CharField(max_length=256, verbose_name='banner link')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='banner created date')),
                ('activity', models.BooleanField(default=False, verbose_name='banner activity')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
            },
        ),
        migrations.CreateModel(
            name='GoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.FileField(upload_to='images/categories')),
                ('deleted', models.BooleanField(verbose_name='Deleted')),
                ('active', models.BooleanField(verbose_name='Active')),
                ('order_index', models.IntegerField(verbose_name='Order Index')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='main.goodcategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Good Category',
                'verbose_name_plural': 'Goods Categories',
                'db_table': 'mp_goods_categories',
            },
        ),
    ]
