# Generated by Django 3.2.8 on 2021-10-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='banner title')),
                ('text', models.CharField(blank=True, max_length=256, null=True, verbose_name='banner text')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/banners', verbose_name='banner image')),
                ('link', models.CharField(max_length=256, verbose_name='banner link')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='banner created date')),
                ('activity', models.BooleanField(default=False, verbose_name='banner activity')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
            },
        ),
    ]
